name: Deploy to GitHub Pages with Astro

on:
 push:
    branches: [ main ]
 workflow_dispatch:

jobs:
 build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v2

 deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ILLUNEXUS }}
          publish_branch: gh-pages
          publish_dir: ./public
